module com.example.livecycle {
    requires javafx.fxml;
    requires jbcrypt;
    requires com.google.gson;
    requires java.sql;
    requires mysql.connector.j;
    requires jdk.httpserver;
    requires org.kordamp.ikonli.core;
    requires org.kordamp.ikonli.javafx;
    requires org.json;
    requires java.mail;
    requires javafx.web;
    requires java.net.http;
    requires jdk.jsobject;
    requires java.desktop;
    requires stripe.java;
    requires java.prefs;
    requires opencv;
    requires javafx.swing;
    requires itextpdf;
    requires okhttp3;
    requires twilio;
    requires com.google.zxing.javase;
    requires org.apache.pdfbox;
    requires org.apache.fontbox;
    requires commons.logging;
    requires com.google.zxing;
    requires com.google.api.client.extensions.jetty.auth;
    requires com.google.api.client.extensions.java6.auth;
    requires com.google.api.client.auth;
    requires google.api.client;
    requires com.google.api.client;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.core;
    requires com.google.api.client.json.gson;
    requires com.google.api.services.calendar;

    opens com.example.livecycle to javafx.fxml;
    exports com.example.livecycle;
    exports com.example.livecycle.entities;
    exports com.example.livecycle.controllers.backoffice;
    opens com.example.livecycle.controllers.backoffice to javafx.fxml;
    exports com.example.livecycle.controllers.frontoffice;
    opens com.example.livecycle.controllers.frontoffice to javafx.fxml;
    exports com.example.livecycle.controllers.auth;
    opens com.example.livecycle.controllers.auth to javafx.fxml;
    exports com.example.livecycle.services;
    opens com.example.livecycle.entities to javafx.base, javafx.fxml;
    exports com.example.livecycle.utils;
    opens com.example.livecycle.utils to javafx.fxml;
}